/*
 * File: app/view/ClothoXmlViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.ClothoXmlViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'ClothoExtXml.controller.GlobalVariables'
    ],

    id: 'mainViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'centerRegion',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            id: 'mainTabset',
                            width: 694,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 613,
                                    width: 818,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Sconti generici',
                                    tabConfig: {
                                        xtype: 'tab',
                                        closeText: ''
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            id: 'vendorData',
                                            maxHeight: 30,
                                            minHeight: 30,
                                            tpl: [
                                                '<div style="padding:5px"> ',
                                                '    <span>Codice:<b>{codice}</b></span>&nbsp;&nbsp;<span>Nome:<b>{nome}</b></span>',
                                                '    &nbsp;&nbsp;<span>Strategia:<b>{strategy}</b></span>',
                                                '</div>'
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            height: 205,
                                            id: 'basicDataPanel',
                                            width: 748,
                                            title: 'Basic Data',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Da'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'A'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Scadenza'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Valore in note3'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Regole di sconto e prezzo',
                                    tabConfig: {
                                        xtype: 'tab',
                                        id: 'tabRegole'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    maxWidth: 160,
                                                    minWidth: 160,
                                                    width: 160,
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'hbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'gridpanel',
                                                            id: 'ruleGridPanel',
                                                            maxWidth: 160,
                                                            minWidth: 160,
                                                            padding: 2,
                                                            width: 160,
                                                            title: 'Lista Regole ',
                                                            enableColumnHide: false,
                                                            enableColumnMove: false,
                                                            enableColumnResize: false,
                                                            viewConfig: {

                                                            },
                                                            columns: [
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: 154,
                                                                    dataIndex: 'string',
                                                                    text: 'Regola'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    hidden: false,
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'vbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            maxHeight: 220,
                                                            minHeight: 220,
                                                            padding: 2,
                                                            bodyPadding: 5,
                                                            title: 'Gestione singola regola',
                                                            items: [
                                                                {
                                                                    xtype: 'fieldset',
                                                                    maxWidth: 300,
                                                                    minWidth: 300,
                                                                    padding: 5,
                                                                    width: 300,
                                                                    title: 'Dati regola di sconto generica',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            anchor: '100%',
                                                                            width: 100,
                                                                            fieldLabel: 'Regola',
                                                                            labelAlign: 'right'
                                                                        },
                                                                        {
                                                                            xtype: 'numberfield',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'Valore',
                                                                            labelAlign: 'right',
                                                                            hideTrigger: true
                                                                        },
                                                                        {
                                                                            xtype: 'datefield',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'Scadenza',
                                                                            labelAlign: 'right'
                                                                        },
                                                                        {
                                                                            xtype: 'combobox',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'Strategia',
                                                                            labelAlign: 'right'
                                                                        }
                                                                    ]
                                                                }
                                                            ],
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'bottom',
                                                                    ui: 'footer',
                                                                    items: [
                                                                        {
                                                                            xtype: 'button',
                                                                            text: 'Salva'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            text: 'Esci senza salvare'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'tabpanel',
                                                            flex: 1,
                                                            padding: 2,
                                                            activeTab: 0,
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    padding: 2,
                                                                    title: 'Sconti',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'string',
                                                                            text: 'Da Fornitore'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            dataIndex: 'number',
                                                                            text: 'Tolleranza'
                                                                        },
                                                                        {
                                                                            xtype: 'datecolumn',
                                                                            dataIndex: 'date',
                                                                            text: 'Scadenza'
                                                                        },
                                                                        {
                                                                            xtype: 'booleancolumn',
                                                                            dataIndex: 'bool',
                                                                            text: 'Prezzo Lordo'
                                                                        }
                                                                    ],
                                                                    viewConfig: {

                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    title: 'Prezzi',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'string',
                                                                            text: 'String'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            dataIndex: 'number',
                                                                            text: 'Number'
                                                                        },
                                                                        {
                                                                            xtype: 'datecolumn',
                                                                            dataIndex: 'date',
                                                                            text: 'Date'
                                                                        },
                                                                        {
                                                                            xtype: 'booleancolumn',
                                                                            dataIndex: 'bool',
                                                                            text: 'Boolean'
                                                                        }
                                                                    ],
                                                                    viewConfig: {

                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    title: 'Prezzo fisso',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'string',
                                                                            text: 'String'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            dataIndex: 'number',
                                                                            text: 'Number'
                                                                        },
                                                                        {
                                                                            xtype: 'datecolumn',
                                                                            dataIndex: 'date',
                                                                            text: 'Date'
                                                                        },
                                                                        {
                                                                            xtype: 'booleancolumn',
                                                                            dataIndex: 'bool',
                                                                            text: 'Boolean'
                                                                        }
                                                                    ],
                                                                    viewConfig: {

                                                                    }
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'west',
                    maxWidth: 200,
                    width: 200,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    height: 200,
                                    hidden: false,
                                    id: 'vendorFormContainer',
                                    maxHeight: 200,
                                    minHeight: 200,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            bodyPadding: 10,
                                            title: 'Gestione  Fornitore',
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    title: 'Dati generali del fornitore',
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            name: 'codice',
                                                            fieldLabel: 'Codice',
                                                            labelAlign: 'right',
                                                            labelWidth: 50,
                                                            hideTrigger: true,
                                                            spinDownEnabled: false,
                                                            spinUpEnabled: false,
                                                            allowDecimals: false,
                                                            decimalPrecision: 0
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            name: 'nome',
                                                            fieldLabel: 'Nome',
                                                            labelAlign: 'right',
                                                            labelWidth: 50,
                                                            size: 60
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            anchor: '100%',
                                                            name: 'strategy',
                                                            fieldLabel: 'Strategia',
                                                            labelAlign: 'right',
                                                            labelWidth: 50
                                                        }
                                                    ]
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    height: 35,
                                                    maxHeight: 35,
                                                    minHeight: 35,
                                                    ui: 'footer',
                                                    layout: {
                                                        align: 'middle',
                                                        pack: 'center',
                                                        padding: '',
                                                        type: 'hbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            iconCls: 'file_save',
                                                            text: 'Salva',
                                                            type: 'submit'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            iconCls: 'cancel',
                                                            text: 'Esci senza salvare',
                                                            type: 'reset',
                                                            listeners: {
                                                                click: {
                                                                    fn: me.onButtonClick,
                                                                    scope: me
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 3,
                                    layout: {
                                        type: 'fit'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'vendorGridPanel',
                                            title: 'Fornitori',
                                            store: 'Vendors',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 50,
                                                    dataIndex: 'codice',
                                                    text: 'Codice',
                                                    format: ''
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 148,
                                                    dataIndex: 'nome',
                                                    text: 'Nome'
                                                }
                                            ],
                                            listeners: {
                                                afterlayout: {
                                                    fn: me.onVendorGridPanelAfterLayout,
                                                    scope: me
                                                },
                                                select: {
                                                    fn: me.onVendorGridPanelSelect,
                                                    scope: me
                                                },
                                                itemdblclick: {
                                                    fn: me.onVendorGridPanelItemDblClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'south',
                    height: 30
                },
                {
                    xtype: 'container',
                    region: 'north',
                    height: 34,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            flex: 2,
                            height: 30,
                            items: [
                                {
                                    xtype: 'button',
                                    width: 53,
                                    text: 'Excel'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Diapason'
                                },
                                {
                                    xtype: 'button',
                                    width: 61,
                                    text: 'Help'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-add-btn',
                                    iconCls: 'file_add',
                                    text: 'Aggiungi',
                                    listeners: {
                                        click: {
                                            fn: me.addRecord,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-modify-btn',
                                    iconCls: 'file_edit',
                                    text: 'Modifica'
                                },
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-delete-btn',
                                    iconCls: 'file_delete',
                                    text: 'Cancella'
                                },
                                {
                                    xtype: 'button',
                                    id: 'bmaintoolbar-save-btn',
                                    iconCls: 'file_save',
                                    text: 'Salva'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        Ext.getCmp('vendorFormContainer').hide()
    },

    onVendorGridPanelAfterLayout: function(abstractcontainer, layout, options) {
        ClothoExtXml.controller.GlobalVariables.setCurrentGrid(abstractcontainer);
    },

    onVendorGridPanelSelect: function(selModel, record, index, options) {
        Ext.getCmp('vendorData').update(record.getData());
    },

    onVendorGridPanelItemDblClick: function(tablepanel, record, item, index, e, options) {
        Ext.getCmp('vendorFormContainer').show()
    },

    addRecord: function(button, e, options) {
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentForm());
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentGrid());
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentRecord());
    }

});