/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    id: 'mainViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'centerRegion',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            width: 694,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 613,
                                    width: 818,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Basic data',
                                    tabConfig: {
                                        xtype: 'tab',
                                        closeText: ''
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    height: 178,
                                                    id: 'vendorForm',
                                                    width: 10004,
                                                    bodyPadding: 10,
                                                    title: 'My Form',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            name: 'pippo',
                                                            fieldLabel: 'Codice'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 205,
                                            id: 'basicDataPanel',
                                            width: 748,
                                            title: 'Basic Data',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Da'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'A'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Scadenza'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Valore in note3'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Regole',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    id: 'ruleGridPanel',
                                                    title: 'My Grid Panel',
                                                    viewConfig: {

                                                    },
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Regole'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            dataIndex: 'number',
                                                            text: 'Number'
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            dataIndex: 'date',
                                                            text: 'Date'
                                                        },
                                                        {
                                                            xtype: 'booleancolumn',
                                                            dataIndex: 'bool',
                                                            text: 'Boolean'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'form',
                                                    width: 382,
                                                    bodyPadding: 10,
                                                    title: 'My Form'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 220,
                                            title: 'Regole',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Da Fornitore'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Tolleranza'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Scadenza'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Prezzo Lordo'
                                                }
                                            ],
                                            viewConfig: {

                                            }
                                        }
                                    ],
                                    tabConfig: {
                                        xtype: 'tab',
                                        id: ''
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'west',
                    width: 295,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 336,
                            id: 'vendorGridPanel',
                            title: 'Fornitori',
                            store: 'Vendors',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'codice',
                                    text: 'Codice',
                                    format: ''
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'nome',
                                    text: 'Nome'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'south',
                    height: 30
                },
                {
                    xtype: 'container',
                    region: 'north',
                    height: 34,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            height: 30,
                            items: [
                                {
                                    xtype: 'button',
                                    width: 53,
                                    text: 'Excel'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Diapason'
                                },
                                {
                                    xtype: 'button',
                                    width: 61,
                                    text: 'Help'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            layout: {
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-add-btn',
                                    iconCls: 'file_add',
                                    text: 'Aggiungi'
                                },
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-modify-btn',
                                    iconCls: 'file_edit',
                                    text: 'Modifica'
                                },
                                {
                                    xtype: 'button',
                                    id: 'maintoolbar-delete-btn',
                                    iconCls: 'file_delete',
                                    text: 'Cancella'
                                },
                                {
                                    xtype: 'button',
                                    id: 'bmaintoolbar-save-btn',
                                    iconCls: 'file_save',
                                    text: 'Salva'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    resetBorders: function() {
        var panelsWithinMyViewport = Ext.ComponentQuery.query('gridpanel, form');
        console.log(panelsWithinMyViewport);
        Ext.Array.each(panelsWithinMyViewport,function(panel){
            panel.setBodyStyle('border-color','');
        })
    }

});