/*
 * File: app/view/RulesAreaPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.RulesAreaPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.rulesAreaPanel',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Regole di sconto e prezzo',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            maxWidth: 160,
                            minWidth: 160,
                            width: 160,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'ruleGridPanel',
                                    maxWidth: 160,
                                    minWidth: 160,
                                    padding: 2,
                                    width: 160,
                                    title: 'Lista Regole ',
                                    enableColumnHide: false,
                                    enableColumnMove: false,
                                    enableColumnResize: false,
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 154,
                                            dataIndex: 'string',
                                            text: 'Regola'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: false,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    maxHeight: 220,
                                    minHeight: 220,
                                    padding: 2,
                                    bodyPadding: 5,
                                    title: 'Gestione singola regola',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            maxWidth: 300,
                                            minWidth: 300,
                                            padding: 5,
                                            width: 300,
                                            title: 'Dati regola di sconto generica',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    width: 100,
                                                    fieldLabel: 'Regola',
                                                    labelAlign: 'right'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Valore',
                                                    labelAlign: 'right',
                                                    hideTrigger: true
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Scadenza',
                                                    labelAlign: 'right'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    anchor: '100%',
                                                    fieldLabel: 'Strategia',
                                                    labelAlign: 'right'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            ui: 'footer',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Salva'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Esci senza salvare'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    flex: 1,
                                    padding: 2,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            padding: 2,
                                            title: 'Sconti',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Da Fornitore'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Tolleranza'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Scadenza'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Prezzo Lordo'
                                                }
                                            ],
                                            viewConfig: {

                                            }
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            title: 'Prezzi',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ],
                                            viewConfig: {

                                            }
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            title: 'Prezzo fisso',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ],
                                            viewConfig: {

                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});