/*
 * File: app/model/Sconto.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.model.Sconto', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'codice'
        },
        {
            name: 'sconto_fornitore'
        },
        {
            name: 'tolleranza'
        },
        {
            name: 'prezzo_lordo'
        },
        {
            name: 'affiliato'
        },
        {
            name: 'affiliato_light'
        },
        {
            name: 'somministrato'
        },
        {
            name: 'prezzo_affiliato'
        },
        {
            name: 'prezzo_affiliato_light'
        },
        {
            name: 'prezzo_somministrato'
        },
        {
            name: 'scadenza'
        }
    ]
});