/*
 * File: app/controller/FocusController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.controller.FocusController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.focusController',

    init: function(application) {
        this.control(
        {'textfield': {'focus':this.fieldGotFocus},
        'gridpanel': {'containerclick':this.containerClicked}
    }
    )
    },

    fieldGotFocus: function(field) {
        console.log('Field has got focus'+field.getName());
        this.resetBorders();
        field.up('form').setBodyStyle('border-color','red');

    },

    resetBorders: function() {
        var panelsWithinMyViewport = Ext.ComponentQuery.query('gridpanel, form');
        Ext.Array.each(panelsWithinMyViewport,function(panel){
            panel.setBodyStyle('border-color','');
        })
    },

    containerClicked: function(view) {
        console.log('Container clicked');
        this.resetBorders();
        view.up('gridpanel').setBodyStyle('border: solid 2px red');
    }

});
